backend:
  name: github
  repo: marvin-hinkley/docsify-demo
  branch: master
  site_domain: confident-northcutt-6648eb.netlify.app
publish_mode: editorial_workflow
media_folder: "docs/media/uploads"
collections:
  - name: "doc" # Used in routes, e.g., /admin/collections/blog
    label: "Documentation Article" # Used in the UI
    folder: "docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}