backend:
  name: github
  repo: marvin-hinkley/docsify-demo
  branch: master
  site_domain: confident-northcutt-6648eb.netlify.app
publish_mode: editorial_workflow
media_folder: "docs/media/uploads"
logo_url: "https://www.aspdotnetstorefront.com/App_Themes/Skin_1/images/adnsf-logo-95-lt-bg.png"
collections:
  - name: "doc" # Used in routes, e.g., /admin/collections/blog
    label: "Documentation Article" # Used in the UI
    folder: "docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'components'
    label: 'Components'
    files:
      - name: "_sidebar"
        label: "Documentation Sidebar"
        file: "docs/_sidebar.md"
        fields:
          - {label: "Links", name: "links", widget: "markdown"}
      - name: "_404"
        label: "404 Page"
        file: "docs/_404.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "_coverpage"
        label: "Cover Page"
        file: "docs/_coverpage.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}